### PR TITLE
u-boot: Enable CONFIG_CMD_SETEXPR for asus-tinker-board

### PR DESCRIPTION
**Pull request by acostach**
This applies to both asus-tinker-board and
asus-tinker-board-s machines

Fixes https://github.com/balena-os/balena-asus-tinker-board/issues/22

### CODE REVIEW

**Comment by imrehg** [comment]
@acostach what does this change do / enable?

**Comment by acostach** [comment]
> @acostach what does this change do / enable?

It helps supporting rollbacks as mentioned above in #22

**Comment by imrehg** [comment]
Sorry, need to learn to read :P

**Comment by floion** [comment]
@resin-jenkins add to whitelist

**Pull request merged**
