### PR TITLE
Add meta-balena as upstream

### PR DESCRIPTION
**Pull request by nazrhom**
Change-type: patch
Signed-off-by: Giovanni Garufi <giovanni@balena.io>

### CODE REVIEW

**Comment by imrehg** [comment]
@nazrhom is this a hard requirement? Or just a nice to have? As for example `balena-raspberrypi` still uses the old name (and I believe relies on Github redirects). Also if using `meta-balena`, why keep the `meta-resin` upstream in the `repo.yml`?

https://github.com/balena-os/balena-raspberrypi/blob/97f127324375be614180167b16339c0483aa0085/repo.yml#L4-L6

**Comment by nazrhom** [comment]
@imrehg there are similar PRs on all device repos that have yet to be approved and merged. Github does redirect but atm VB is triggered by the comment `Update meta-resin to ...` adding both would allow it to react to `Update meta-balena to..` as well

**Comment by imrehg** [comment]
@nazrhom that makes sense! If okay, I'll pull get this into an upcoming PR together with other stuff!

**Comment by imrehg** [comment]
Superseded by #25

**Pull request closed without merging**
